### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by sucof** [zhiyicx/plus-component-channel#1]
php artisan package:handle 安装方式还不行吗？以前的php artisan component方式也是移除了，请问有更详细的文档吗？

**Comment by this-BaiShi** [comment]
php artisan package:handle channel install

**Comment by this-BaiShi** [comment]
安装注入的文档，之后会完善，频道这个扩展包需要重构和增加功能

**Comment by sucof** [comment]
使用php artisan package:handle channel install指令，还是会产生如下错误：
[ReflectionException]                                                        
  Class Zhiyi\Component\ZhiyiPlus\PlusComponentChannel\Installer\PcPackageHan  
  dler does not exist

**Comment by this-BaiShi** [comment]
新的提交修复了这个问题，另外文档里写了一下基本安装
